require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/adopts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Adopt. As you add validations to Adopt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Adopt.create! valid_attributes
      get adopts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      adopt = Adopt.create! valid_attributes
      get adopt_url(adopt)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_adopt_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      adopt = Adopt.create! valid_attributes
      get edit_adopt_url(adopt)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Adopt" do
        expect {
          post adopts_url, params: { adopt: valid_attributes }
        }.to change(Adopt, :count).by(1)
      end

      it "redirects to the created adopt" do
        post adopts_url, params: { adopt: valid_attributes }
        expect(response).to redirect_to(adopt_url(Adopt.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Adopt" do
        expect {
          post adopts_url, params: { adopt: invalid_attributes }
        }.to change(Adopt, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post adopts_url, params: { adopt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested adopt" do
        adopt = Adopt.create! valid_attributes
        patch adopt_url(adopt), params: { adopt: new_attributes }
        adopt.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the adopt" do
        adopt = Adopt.create! valid_attributes
        patch adopt_url(adopt), params: { adopt: new_attributes }
        adopt.reload
        expect(response).to redirect_to(adopt_url(adopt))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        adopt = Adopt.create! valid_attributes
        patch adopt_url(adopt), params: { adopt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested adopt" do
      adopt = Adopt.create! valid_attributes
      expect {
        delete adopt_url(adopt)
      }.to change(Adopt, :count).by(-1)
    end

    it "redirects to the adopts list" do
      adopt = Adopt.create! valid_attributes
      delete adopt_url(adopt)
      expect(response).to redirect_to(adopts_url)
    end
  end
end
